// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Data;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Shared.SpContentDto", b =>
                {
                    b.Property<string>("CtoBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CtoDurationBanner")
                        .HasColumnType("int");

                    b.Property<bool>("CtoEstado")
                        .HasColumnType("bit");

                    b.Property<int?>("CtoIdContenidoPk")
                        .HasColumnType("int");

                    b.Property<string>("CtoTextoBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtoTipoContenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CtoTipoContenidoFk")
                        .HasColumnType("int");

                    b.Property<string>("CtoTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtoVideo")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SpContentDto");
                });

            modelBuilder.Entity("Models.TblBanner", b =>
                {
                    b.Property<int>("BnrIdBannerPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bnr_IdBannerPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BnrIdBannerPk"));

                    b.Property<int>("BnrDuracion")
                        .HasColumnType("int")
                        .HasColumnName("bnr_duracion");

                    b.Property<bool>("BnrEstado")
                        .HasColumnType("bit")
                        .HasColumnName("bnr_estado");

                    b.Property<int>("BnrIdContenidoFk")
                        .HasColumnType("int")
                        .HasColumnName("bnr_idContenidoFk");

                    b.Property<string>("BnrRutaAcceso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bnr_rutaAcceso");

                    b.Property<string>("BnrTexto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bnr_texto");

                    b.HasKey("BnrIdBannerPk")
                        .HasName("PK__TblBanne__426D162CE02E3A3D");

                    b.HasIndex("BnrIdContenidoFk");

                    b.ToTable("TblBanner", (string)null);
                });

            modelBuilder.Entity("Models.TblContenido", b =>
                {
                    b.Property<int>("CtoIdContenidoPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cto_IdContenidoPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CtoIdContenidoPk"));

                    b.Property<bool>("CtoEstado")
                        .HasColumnType("bit")
                        .HasColumnName("cto_estado");

                    b.Property<int>("CtoTipoContenidoFk")
                        .HasColumnType("int")
                        .HasColumnName("cto_tipoContenidoFk");

                    b.Property<string>("CtoTitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cto_titulo");

                    b.HasKey("CtoIdContenidoPk")
                        .HasName("PK__TblConte__11ED543B015314DD");

                    b.HasIndex("CtoTipoContenidoFk");

                    b.ToTable("TblContenido", (string)null);
                });

            modelBuilder.Entity("Models.TblDatosPersona", b =>
                {
                    b.Property<int>("DpIdDatosPersonaPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dp_IdDatosPersonaPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DpIdDatosPersonaPk"));

                    b.Property<string>("DpApellido1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dp_apellido1");

                    b.Property<string>("DpApellido2")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dp_apellido2");

                    b.Property<bool>("DpEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dp_estado");

                    b.Property<string>("DpNombre1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dp_nombre1");

                    b.Property<string>("DpNombre2")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dp_nombre2");

                    b.HasKey("DpIdDatosPersonaPk")
                        .HasName("PK__TblDatos__0B8745621CD910D3");

                    b.ToTable("TblDatosPersona", (string)null);
                });

            modelBuilder.Entity("Models.TblDicRolesSistema", b =>
                {
                    b.Property<int>("RsIdRolSistemaPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rs_IdRolSistemaPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsIdRolSistemaPk"));

                    b.Property<bool>("RsEstado")
                        .HasColumnType("bit")
                        .HasColumnName("rs_estado");

                    b.Property<string>("RsNombreRol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("rs_nombreRol");

                    b.HasKey("RsIdRolSistemaPk")
                        .HasName("PK__TblDicRo__8FBF7D6F97F33995");

                    b.ToTable("TblDicRolesSistema", (string)null);
                });

            modelBuilder.Entity("Models.TblDicTipoContenido", b =>
                {
                    b.Property<int>("TctoIdTipoContenidoPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tcto_IdTipoContenidoPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TctoIdTipoContenidoPk"));

                    b.Property<string>("TctoDescripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tcto_descripcion");

                    b.Property<bool>("TctoEstado")
                        .HasColumnType("bit")
                        .HasColumnName("tcto_estado");

                    b.Property<string>("TctoTipoContenido")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("tcto_tipoContenido");

                    b.HasKey("TctoIdTipoContenidoPk")
                        .HasName("PK__TblDicTi__C738477F6652813B");

                    b.ToTable("TblDicTipoContenido", (string)null);
                });

            modelBuilder.Entity("Models.TblProgramacionContenido", b =>
                {
                    b.Property<int>("PcoIdProgramacionPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pco_IdProgramacionPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PcoIdProgramacionPk"));

                    b.Property<bool>("PcoEstado")
                        .HasColumnType("bit")
                        .HasColumnName("pco_estado");

                    b.Property<TimeOnly>("PcoHoraProgramada")
                        .HasColumnType("time")
                        .HasColumnName("pco_horaProgramada");

                    b.Property<int>("PcoIdContenidoFk")
                        .HasColumnType("int")
                        .HasColumnName("pco_idContenidoFk");

                    b.HasKey("PcoIdProgramacionPk")
                        .HasName("PK__TblProgr__5AFE44BACCAC05ED");

                    b.HasIndex("PcoIdContenidoFk");

                    b.ToTable("TblProgramacionContenido", (string)null);
                });

            modelBuilder.Entity("Models.TblUsuario", b =>
                {
                    b.Property<int>("UsIdUsuarioPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("us_IdUsuarioPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsIdUsuarioPk"));

                    b.Property<string>("UsAlias")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("us_alias");

                    b.Property<string>("UsContrasena")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("us_contrasena");

                    b.Property<int>("UsDatosPersonaFk")
                        .HasColumnType("int")
                        .HasColumnName("us_datosPersonaFk");

                    b.Property<bool>("UsEstado")
                        .HasColumnType("bit")
                        .HasColumnName("us_estado");

                    b.Property<int>("UsRolSistemaFk")
                        .HasColumnType("int")
                        .HasColumnName("us_rolSistemaFk");

                    b.HasKey("UsIdUsuarioPk")
                        .HasName("PK__TblUsuar__EA793E97B5F5D1FD");

                    b.HasIndex("UsDatosPersonaFk");

                    b.HasIndex("UsRolSistemaFk");

                    b.ToTable("TblUsuarios");
                });

            modelBuilder.Entity("Models.TblVideo", b =>
                {
                    b.Property<int>("VdoIdVideoPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vdo_IdVideoPk");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VdoIdVideoPk"));

                    b.Property<bool>("VdoEstado")
                        .HasColumnType("bit")
                        .HasColumnName("vdo_estado");

                    b.Property<int>("VdoIdContenidoFk")
                        .HasColumnType("int")
                        .HasColumnName("vdo_idContenidoFk");

                    b.Property<string>("VdoRutaAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vdo_rutaAcceso");

                    b.HasKey("VdoIdVideoPk")
                        .HasName("PK__TblVideo__150E869A49468549");

                    b.HasIndex("VdoIdContenidoFk");

                    b.ToTable("TblVideo", (string)null);
                });

            modelBuilder.Entity("Models.TblBanner", b =>
                {
                    b.HasOne("Models.TblContenido", "BnrIdContenidoFkNavigation")
                        .WithMany("TblBanners")
                        .HasForeignKey("BnrIdContenidoFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblBanner__bnr_e__5070F446");

                    b.Navigation("BnrIdContenidoFkNavigation");
                });

            modelBuilder.Entity("Models.TblContenido", b =>
                {
                    b.HasOne("Models.TblDicTipoContenido", "CtoTipoContenidoFkNavigation")
                        .WithMany("TblContenidos")
                        .HasForeignKey("CtoTipoContenidoFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblConten__cto_t__44FF419A");

                    b.Navigation("CtoTipoContenidoFkNavigation");
                });

            modelBuilder.Entity("Models.TblProgramacionContenido", b =>
                {
                    b.HasOne("Models.TblContenido", "PcoIdContenidoFkNavigation")
                        .WithMany("TblProgramacionContenidos")
                        .HasForeignKey("PcoIdContenidoFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblProgra__pco_e__4D94879B");

                    b.Navigation("PcoIdContenidoFkNavigation");
                });

            modelBuilder.Entity("Models.TblUsuario", b =>
                {
                    b.HasOne("Models.TblDatosPersona", "UsDatosPersonaFkNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("UsDatosPersonaFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblUsuari__us_da__3F466844");

                    b.HasOne("Models.TblDicRolesSistema", "UsRolSistemaFkNavigation")
                        .WithMany("TblUsuarios")
                        .HasForeignKey("UsRolSistemaFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblUsuari__us_ro__403A8C7D");

                    b.Navigation("UsDatosPersonaFkNavigation");

                    b.Navigation("UsRolSistemaFkNavigation");
                });

            modelBuilder.Entity("Models.TblVideo", b =>
                {
                    b.HasOne("Models.TblContenido", "VdoIdContenidoFkNavigation")
                        .WithMany("TblVideos")
                        .HasForeignKey("VdoIdContenidoFk")
                        .IsRequired()
                        .HasConstraintName("FK__TblVideo__vdo_id__47DBAE45");

                    b.Navigation("VdoIdContenidoFkNavigation");
                });

            modelBuilder.Entity("Models.TblContenido", b =>
                {
                    b.Navigation("TblBanners");

                    b.Navigation("TblProgramacionContenidos");

                    b.Navigation("TblVideos");
                });

            modelBuilder.Entity("Models.TblDatosPersona", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("Models.TblDicRolesSistema", b =>
                {
                    b.Navigation("TblUsuarios");
                });

            modelBuilder.Entity("Models.TblDicTipoContenido", b =>
                {
                    b.Navigation("TblContenidos");
                });
#pragma warning restore 612, 618
        }
    }
}
